#!/usr/bin/env bash
# Output: The subdomain [SUB_DOMAIN] is a [RECORD_TYPE] record and points to [DESTINATION]

pr_domains ()
{
    echo -n "The subdomain $2"
    dig "$2.$1" | grep -A1 'ANSWER SECTION' | grep "$2" | awk '{ print "is a " $4 " record and points to " $5}'
}

domain=$1
if [ $# -eq 2 ]
then
    pr_domains $domain $2
else
    for subdomain in www lb-01 web-01 web-02
    do
        pr_domains $domain $subdomain
    done
fi
