#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me

sudo apt -y update
sudo apt -y install nginx
echo "Hello World" > /var/www/html/index.html
new_string="line number 1\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=cXR_nUy-YhY permanent;"
sed -i "s/string_to_replace/$new_string/" /etc/nginx/sites-avaible/default

service nginx restart
