#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me

sudo apt -y update
sudo apt -y install nginx
echo "Hello World" > /var/www/html/index.html
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=cXR_nUy-YhY permanent;"
sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sed -i 's/listen 80 default_server;/a error_page 404 /custom_404.html;\nlocation = /custom_404.html {\nroot /usr/share/nginx/html;\ninternal;\n}' /etc/nginx/sites-available/default

service nginx restart
