#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt-get -y update
sudo apt-get install haproxy -y
echo "
frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server host_1 54.210.85.213:80 check
    server host_2 54.91.141.251:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
