#!/usr/bin/env bash
# Script to create Back up on Mysql

mysqldump -uroot -p"$1" --all-databases --single-transaction --quick --lock-tables=false > backup.sql
tar -cvzf "$(date +%d-%m-%Y)".tar.gz backup.sql
