#!/usr/bin/env bash
# Let’s install the ufw firewall and setup a few rules on web-01.
sudo apt update -y
sudo apt install ufw -y
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow ssh
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw enable
